count_spacers:
    # For the files and paths below, use absolute paths e.g. /Users/Harry/fastq-data or
    # paths relative to the `toolkit` directory.
    # If you're using the Docker container, replace your home path with /Home.  For example, if you
    # want to use the folder /Users/Harry/fastq-data, you would replace it with /Home/fastq-data.

    library_file: data/examples/count_spacers/example_library.csv
    input_folder: data/examples/count_spacers

    # Output folder
    output_folder: analysis/examples/count_spacers

    ### Analysis parameters
    sample: tkov3
    # presence of guanine before spacer (yes/no)
    guide_g: yes
    # start index of key region
    key_region_start: 30
    # end index of key region
    key_region_end: 55
    # identifies the sequence before the guide to determine the guide position
    key_region_sequence: CCC


recombination:
    # Change these two values to the folders you prefer - use absolute paths e.g. /Users/Harry/fastq-data or
    # paths relative to the `toolkit` directory.
    # If you're using the Docker container, replace your home path with /Home.  For example, if you
    # want to use the folder /Users/Harry/fastq-data, you would replace it with /Home/fastq-data.

    input_folder: data/examples/recombination
    output_folder: analysis/examples/recombination

    # The number of bases to retrieve before the seed sequence
    HEAD: 10

    # The number of bases to retrieve after the seed sequences
    TAIL: 10

    seed_sequences:
        loxP: ATAACTTCGTATAGCATACATTATACGAAGTTAT
        lox2272: ATAACTTCGTATAGGATACTTTATACGAAGTTAT


serotypes:
    # Change these two values to the folders you prefer - use absolute paths e.g. /Users/Harry/fastq-data or
    # paths relative to the `toolkit` directory.
    # If you're using the Docker container, replace your home path with /Home.  For example, if you
    # want to use the folder /Users/Harry/fastq-data, you would replace it with /Home/fastq-data.

    input_folder: data/examples/serotypes
    output_folder: analysis/examples/serotypes

    # These are the signatures that will be matched. The first part is the name, the part in brackets contains the
    # actual signatures, separated by a comma (each serotype can have multiple signatures)

    signatures:
        AAV1:
            - AGTGCTTCAACGGGGGCCAG
            - GGGCGTGAATCCATCATCAACCCTGG
            - CCGGAGCTTCAAACACTGCATTGGACAAT
        AAV2:
            - AGGCAACAGACAAGCAGCTACC
            - AACAGACAAGCAGCTACCGCA
        AAV5:
            - TCCAAGCCTTCCACCTCGTCAGACGCCGAA
            - CACCAACAACCAGAGCTCCACCACTG
            - GCCCGTCAGCAGCTTCATC
        AAV7:
            - AGTGAAACTGCAGGTAGTACC
        AAV8:
            - GCAAAACACGGCTCCTCAAAT
            - CAGCAAGCGCTGGAACCCCGAGATCCAGTA
            - AAATACCATCTGAATGGAAGAAATTCATTG
            - CGTGGCAGATAACTTGCAGC
            - ATCCTCCGACCACCTTCAACC
        AAV9:
            - AGTGCCCAAGCACAGGCGCA
            - ATCTCTCAAAGACTATTAAC
            - GGCGAGCAGTCTTCCAGGCA
        AAVrh10:
            - CTACAAATCTACAAATGTGGACTTTG
        PHPeB:
            - CTTTGGCGGTGCCTTTTAAGGCACAGGCGCAGA
        PHPs:
            - AGGCGGTTAGGACGTCTTTGGCACAGGCGCAGA
        AAVrg:
            - TAGCAGACCAAGACTACACAAAAACTGCT
